# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28b1ba8d70dec115ce1e78b0c428a8cfe32e12106d8dbf1e8950e4a03a00796a6547c9185f2f04b60fccd018d5cabf07e279a88059bc184b4f4c026ccd90b81b

test:
  secret_key_base: cf1ab9c0c4ed4e809f724b81aee92b6dded2829b5cc290fa0128e5d1bf5f0b2d9c2fff86c163a948d5e2f2fbde22d2d2d36b2f797d9bb35fd4c35a95d2b11eac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
